name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Feat'
    labels:
      - 'feat'
  - title: '🧑‍🔧 Fix'
    labels:
      - 'fix'
  - title: '👍️ Refactor'
    labels:
      - 'refactor'
  - title: '✅ Test'
    labels:
      - 'test'
  - title: '📔 Docs'
    labels:
      - 'docs'
  - title: '🖊️ chore'
    labels:
      - 'chore'
  - title: '📦 dependencies'
    labels:
      - 'dependencies'
autolabeler:
  - label: feat
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: fix
    branch:
      - '/^fix[/-].+/'
  - label: refactor
    branch:
      - '/(refactor|refactoring)[/-].+/'
  - label: test
    branch:
      - '/^test[/-].+/'
  - label: docs
    branch:
      - '/doc(umentation)[/-].+/'
  - label: chore
    branch:
      - '/^chore[/-].+/'
  - label: dependencies
    branch:
      - '/^dependencies[/-].+/'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'exclude from changelog'
template: |
  ## Changes

  $CHANGES
