name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
#    types: [opened, reopened, synchronize]
    types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "publish main"
      - run: echo ${GITHUB_TOKEN}
      - run: echo ${{ secrets.GITHUB_TOKEN }}