name: "Publish release"
on:
  release:
    types: [published]
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          path: main
        env:
          ref: ${{github.event.pull_request.head.ref}}
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo '${{ toJson(github) }}'
#          echo '${{ toJson(github.event) }}'
#          git checkout release
#          git branch
#      - run: echo '${{ toJson(github.event) }}'
#      - run: git status
#      - run: git branch
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  published:
    runs-on: ubuntu-latest
    steps:
      - run: echo "publish release"