name: "Publish release"
on:
  release:
    types: [published]
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: git status
      - run: git branch
      - run: git checkout -b ${github.ref}/release origin/${github.ref}/release
      - run: git branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  published:
    runs-on: ubuntu-latest
    steps:
      - run: echo "publish release"