name: "Publish release"

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: yugo-ibuki/github-actions
          path: release
      - run: |
          git config --global user.email "y.ibuki91@gmail.com"
          git config --global user.name "yugo-ibuki"
#          echo '${{ toJson(github) }}'
          git --version
          git checkout release
#          echo '${{ toJson(github.event) }}'
#          git checkout release
#          git branch
#      - run: echo '${{ toJson(github.event) }}'
#      - run: git status
#      - run: git branch
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  published:
    runs-on: ubuntu-latest
    steps:
      - run: echo "publish release"