name: "Publish release"
on:
  release:
    types: [published]
jobs:

  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          git checkout release
          git add .
          git commit -m "release"
          git pull
          git push origin release -f
          git checkout main

  published:
    runs-on: ubuntu-latest
    steps:
      - run: echo "publish release"